/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/10storey.glb -o src/components/game/10storeyAsset.tsx -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import type { GLTF } from 'three-stdlib'

type GroupProps = ThreeElements['group']

type GLTFResult = GLTF & {
  nodes: {
    mesh_node: THREE.Mesh
  }
  materials: Record<string, THREE.Material>
}

export function Model(props: GroupProps) {
  const { nodes, materials } = useGLTF('/models/10storey.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_node.geometry} material={nodes.mesh_node.material} position={[-0.001, -0.001, -0.002]} scale={0.95} />
    </group>
  )
}

useGLTF.preload('/models/10storey.glb')
