/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/car.glb -o src/components/game/CarAsset.tsx -r public
*/

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import type { GLTF } from 'three-stdlib'

type GroupProps = ThreeElements['group']

type GLTFResult = GLTF & {
  nodes: {
    mesh_node: THREE.Mesh
  }
  materials: Record<string, THREE.Material>
}

export function Model(
  props: GroupProps & { color?: string }
) {
  const { nodes } = useGLTF('/models/car.glb') as unknown as GLTFResult
  const { color, ...groupProps } = props

  // Clone the baked-in material so we don't mutate the shared cached asset,
  // then tint it — color multiplies against any existing texture on the mesh.
  const material = useMemo(() => {
    const base = nodes.mesh_node.material as THREE.MeshStandardMaterial
    const cloned = base.clone()
    if (color) cloned.color.set(color)
    return cloned
  }, [nodes, color])

  return (
    <group {...groupProps} dispose={null}>
      <mesh geometry={nodes.mesh_node.geometry} material={material} position={[0, -0.002, -0.002]} scale={0.95} />
    </group>
  )
}

useGLTF.preload('/models/car.glb')