/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/palmtree1.glb -o src/components/game/palmtree1Asset.tsx -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_node: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/palmtree1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_node.geometry} material={nodes.mesh_node.material} position={[0.004, -0.006, -0.001]} scale={0.919} />
    </group>
  )
}

useGLTF.preload('/models/palmtree1.glb')
